### ISSUE TITLE
AWSLogsClient is always defaulted to us-east-1

### ISSUE THREAD

**Issue by VenkiMit04** [aws/aws-sdk-java#1221]
Though the region is set in .aws config file, its always defaulting to us-east-1.

**Comment by millems** [comment]
Howdy! Could you confirm which version of the SDK that you are using, how you are creating the AWSLogsClient and the content of your .aws config file?

**Comment by VenkiMit04** [comment]
I am using the aws SDK version 1.9.18. I have set the accessKey and secretKey in the .aws/credential and region in .aws/config.
<dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
        <version>1.9.18</version>
    </dependency>

**Comment by millems** [comment]
Can you post the content of these files, minus the keys? 

There were bugs fixed in the profile loading code between 1.9 and 1.11 if it isn't too much effort to upgrade.

**Comment by VenkiMit04** [comment]
Below are the contents of config and credentials file;

**config:**
[default]
region = us-west-2

**credentials:**
[default]
aws_access_key_id = XXXXXXX
aws_secret_access_key = XXXXXX

**Comment by millems** [comment]
It appears region loading was actually not available in version 1.9 of the SDK. You will need to upgrade to the latest version to get that functionality.

**Comment by VenkiMit04** [comment]
I have tried with version "1.11.160" but still facing the same issue. Its still writing logs to "us-east-1" instead of "us-west-2".

**Comment by millems** [comment]
Hm... Are the credentials being loaded just fine? Have you confirmed that the process has read access to the config file?

**Comment by VenkiMit04** [comment]
Credentials are loaded fine. I can see the logs in us-east-1 region.

**Comment by millems** [comment]
Can you share the code you are using to create the `AWSLogsClient`?

**Comment by VenkiMit04** [comment]
I am using the parameterless constructor.
this.awsLogsClient = new AWSLogsClient();

**Comment by shorea** [comment]
The constructors do not detect the region from the environment. You'll need to use the fluent builders for that functionality. See https://aws.amazon.com/blogs/developer/fluent-client-builders/ and http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html.

If you are using named profiles there is an unfortunate inconsistency with the CLI described in https://github.com/aws/aws-sdk-java/issues/1083. If you are affected by that the current suggested workaround is to duplicate the profiles.

**Comment by varunnvs92** [comment]
Last comment by shorea@ should answer the question. Feel free to reopen if you have more questions.
